### ISSUE TITLE
Unable to setup tailor 

### ISSUE THREAD

**Issue by FrancoisPerez** [bitcraft/tailor#1]
Hello,

Is a run the python "setup.py sdist upload -r pypi" command, I get the following error 

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    "Topic :: Multimedia :: Graphics :: Capture :: Digital Camera"
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\upload.py", line 60, in run
    self.upload_file(command, pyversion, filename)
  File "C:\Python27\lib\distutils\command\upload.py", line 70, in upload_file
    raise AssertionError("unsupported schema " + schema)
AssertionError: unsupported schema

It looks to be related with the "upload -r pypi"; where "pypi" should be a url

Can you help me on that one ?

**Comment by bitcraft** [comment]
Thank you for your interest in Tailor. There is no setup required. The
command that you entered is for the package owner, me. The project is
Python 3 only. Please use "python3 run_local.py" to run it.
