### ISSUE TITLE
tailor hangs up after three photos

### ISSUE THREAD

**Issue by TheDigitalCat** [bitcraft/tailor#8]
Hello!
I try to execute photobooth with tailor.
i use ubuntu 16.04 + pyenv + python 3.6.5

python ./run_local.py 

```

DEBUG:tailor.platform.unix:releasing camera from gvfs...
DEBUG:tailor.launcher:starting process service_cmd
DEBUG:tailor.launcher:starting process kiosk_server_cmd
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:tailor.launcher:starting process kiosk_cmd
[INFO   ] [Logger      ] Record log in /home/zz/.kivy/logs/kivy_18-06-12_22.txt
INFO:kivy:[Logger      ] Record log in /home/zz/.kivy/logs/kivy_18-06-12_22.txt
[INFO   ] [Kivy        ] v1.9.1
INFO:kivy:[Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.6.5 (default, Jun 11 2018, 23:03:46) 
[GCC 5.4.0 20160609]
INFO:kivy:[Python      ] v3.6.5 (default, Jun 11 2018, 23:03:46) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 179 symbols loaded
INFO:kivy:[Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
INFO:kivy:[OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
INFO:kivy:[Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 17.2.8'>
INFO:kivy:[GL          ] OpenGL version <b'3.0 Mesa 17.2.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
INFO:kivy:[GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
INFO:kivy:[GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
INFO:kivy:[GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
INFO:kivy:[GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
INFO:kivy:[GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
INFO:kivy:[GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
INFO:kivy:[Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
INFO:kivy:[Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
INFO:kivy:[Loader      ] using a thread pool of 2 workers
[INFO   ] [Text        ] Provider: sdl2
INFO:kivy:[Text        ] Provider: sdl2
[CRITICAL] [Camera      ] Unable to find any valuable Camera provider at all!
pygst - ModuleNotFoundError: No module named 'pygst'
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/camera/camera_pygst.py", line 15, in <module>
    import pygst

opencv - ModuleNotFoundError: No module named 'cv'
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/camera/camera_opencv.py", line 20, in <module>
    import cv

CRITICAL:kivy:[Camera      ] Unable to find any valuable Camera provider at all!
pygst - ModuleNotFoundError: No module named 'pygst'
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/camera/camera_pygst.py", line 15, in <module>
    import pygst

opencv - ModuleNotFoundError: No module named 'cv'
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/core/camera/camera_opencv.py", line 20, in <module>
    import cv

[INFO   ] [GL          ] NPOT texture support is available
INFO:kivy:[GL          ] NPOT texture support is available
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:08:00] "GET /files HTTP/1.1" 200 -
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event5
INFO:kivy:[ProbeSysfs  ] device match: /dev/input/event5
[INFO   ] [MTD         ] Read event from </dev/input/event5>
INFO:kivy:[MTD         ] Read event from </dev/input/event5>
[INFO   ] [Base        ] Start application main loop
INFO:kivy:[Base        ] Start application main loop
 Exception in thread Thread-2:
WARNING:kivy:stderr: Exception in thread Thread-2:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
WARNING:kivy:stderr:   File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
WARNING:kivy:stderr:   File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
WARNING:kivy:stderr:     self._target(*self._args, **self._kwargs)
   File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
WARNING:kivy:stderr:   File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/input/providers/mtdev.py", line 219, in _thread_run
     _device = Device(_fn)
WARNING:kivy:stderr:     _device = Device(_fn)
   File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/lib/mtdev.py", line 131, in __init__
WARNING:kivy:stderr:   File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
WARNING:kivy:stderr:     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 PermissionError: [Errno 13] Permission denied: '/dev/input/event5'
WARNING:kivy:stderr: PermissionError: [Errno 13] Permission denied: '/dev/input/event5'
 
WARNING:kivy:stderr: 
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:08:01] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:08:06] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:08:11] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:08:16] "GET /files HTTP/1.1" 200 -


```

Appears black window with stars + 2 buttons. I press start. 

```
DEBUG:tailor.picker:transitioning state ('normal', 'preview')
DEBUG:tailor.camera:starting the preview handler

```

after 3 photos i have 

```
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:07] "GET /files HTTP/1.1" 200 -
Task exception was never retrieved
future: <Task finished coro=<ServiceApp.camera_preview_threaded_queue() done, defined at /home/zz/py_booth/tailor/tailor/apps/service/service_app.py:180> exception=GPhoto2Error('[-1] Unspecified error',)>
Traceback (most recent call last):
  File "/home/zz/py_booth/tailor/tailor/apps/service/service_app.py", line 208, in camera_preview_threaded_queue
    image = await camera.download_preview()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 119, in download_preview
    return await self.capture_preview()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 86, in capture_preview
    file = gp.check_result(gp.gp_camera_capture_preview(self._camera, self._context))
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/gphoto2/result.py", line 159, in check_result
    raise gphoto2.GPhoto2Error(error)
gphoto2.GPhoto2Error: [-1] Unspecified error
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:12] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:17] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:22] "GET /files HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/zz/py_booth/tailor/tailor/apps/service/session.py", line 224, in start
    raw_image = await camera.download_capture()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 124, in download_capture
    return await self.capture_image()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 110, in capture_image
    await future
  File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 97, in capture
    path = gp.check_result(gp.gp_camera_capture(self._camera, gp.GP_CAPTURE_IMAGE, self._context))
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/gphoto2/result.py", line 159, in check_result
    raise gphoto2.GPhoto2Error(error)
gphoto2.GPhoto2Error: [-110] I/O in progress
Traceback (most recent call last):
  File "/home/zz/py_booth/tailor/tailor/apps/service/session.py", line 224, in start
    raw_image = await camera.download_capture()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 124, in download_capture
    return await self.capture_image()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 110, in capture_image
    await future
  File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 97, in capture
    path = gp.check_result(gp.gp_camera_capture(self._camera, gp.GP_CAPTURE_IMAGE, self._context))
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/gphoto2/result.py", line 159, in check_result
    raise gphoto2.GPhoto2Error(error)
gphoto2.GPhoto2Error: [-110] I/O in progress
Traceback (most recent call last):
  File "/home/zz/py_booth/tailor/tailor/apps/service/session.py", line 224, in start
    raw_image = await camera.download_capture()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 124, in download_capture
    return await self.capture_image()
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 110, in capture_image
    await future
  File "/home/zz/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zz/py_booth/tailor/tailor/tailor/plugins/gphoto2_camera.py", line 97, in capture
    path = gp.check_result(gp.gp_camera_capture(self._camera, gp.GP_CAPTURE_IMAGE, self._context))
  File "/home/zz/.pyenv/versions/py36/lib/python3.6/site-packages/gphoto2/result.py", line 159, in check_result
    raise gphoto2.GPhoto2Error(error)
gphoto2.GPhoto2Error: [-110] I/O in progress
Task exception was never retrieved
future: <Task finished coro=<ServiceApp.wait_for_socket_open_trigger() done, defined at /home/zz/py_booth/tailor/tailor/apps/service/service_app.py:152> exception=RuntimeError()>
Traceback (most recent call last):
  File "/home/zz/py_booth/tailor/tailor/apps/service/service_app.py", line 157, in wait_for_socket_open_trigger
    await self.session.start(camera, template_graph_root)
  File "/home/zz/py_booth/tailor/tailor/apps/service/session.py", line 232, in start
    raise RuntimeError
RuntimeError
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:27] "GET /files HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jun/2018 05:13:32] "GET /files HTTP/1.1" 200 -
```

what can i do?

**Comment by bitcraft** [comment]
> gphoto2.GPhoto2Error: [-110] I/O in progress

What model camera are you using?  Are you certain it is supported by libgphoto2?

**Comment by neznae4ko** [comment]
canon 550d

**Comment by neznae4ko** [comment]
tailor lets see live view, it can take 3 photos, and hangs after

**Comment by bitcraft** [comment]
There are a few possible problems here.  This line tells me something is too slow/fast:
> gphoto2.GPhoto2Error: [-110] I/O in progress

How much time do you have between pictures?  Are you using USB 2.0?  RAW images are not supported, so verify that your camera is not sending RAW photos (even RAW + JPG) could cause problems.

**Comment by neznae4ko** [comment]
Yes. RAW + JPG is enable in my camera. I will disable it and try today. 

I use usb3.0/

**Comment by bitcraft** [comment]
Sounds great!  I wish RAW would work, but the transfer is just too slow.  It might be possible sometime in the future to enable RAW+JPG, and download all the RAWS at some other time, but for now its just not possible with the API.
